server:
  port: 8081
spring:
  application:
    name: user-center-wjh
  zipkin:
    base-url: http://localhost:9411/
    discoveryClientEnabled: false
    sleuth:
      sampler:
        # 抽样率，默认是0.1（10%）
        probability: 1.0

  cloud:
    nacos:
      discovery:
        server-addr: 47.115.60.46:8848
#        namespace: 10e5a9a3-05ce-457f-b2a3-02bcfe1b512d
#        metadata:
#          instance: cc
#          hello: world
#          version: 1.0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user_content?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

rocketmq:
  name-server: 106.15.234.237:9876

jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600